# Generated by Django 5.0.2 on 2024-03-16 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates_basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='correo',
            new_name='correo_admin',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='fecha',
            new_name='fecha_admin',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='nombre',
            new_name='nombre_admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='correo',
            new_name='correo_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fecha',
            new_name='fecha_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nombre',
            new_name='nombre_user',
        ),
        migrations.AlterField(
            model_name='user',
            name='id_User',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dates_basic.admin'),
        ),
    ]
